"""Report generation for grievance audits"""
from datetime import datetime, timedelta
from typing import Dict, List

class ReportGenerator:
    """Generate markdown audit reports"""
    
    def generate_markdown_report(self, stats: Dict, authority: Dict) -> str:
        """Generate weekly audit report in markdown"""
        week_start = datetime.now() - timedelta(days=7)
        week_end = datetime.now()
        
        report = f"""# {authority['name']} Grievance Redressal Audit Report
## Weekly Report: {week_start.strftime('%B %d')} - {week_end.strftime('%B %d, %Y')}

---

## 1. Executive Summary

| Metric | Value |
|--------|-------|
| **Total Complaints** | {stats['total_complaints']} |
| **Total Responses** | {stats['total_responses']} |
| **Response Rate** | {self._calculate_rate(stats['total_responses'], stats['total_complaints'])} |
| **Avg Response Time** | {stats.get('avg_response_time', 'N/A')} hours |

---

## 2. Category Breakdown

"""
        
        # Add category breakdown
        for cat in stats.get('categories', []):
            report += f"- **{cat['category'].title()}**: {cat['count']} complaints\n"
        
        report += f"""
---

## 3. Analysis

Based on the {stats['total_complaints']} complaints received this week:

"""
        
        if stats['total_responses'] == 0:
            report += "⚠️ **No responses recorded** - This is a critical gap in grievance redressal.\n\n"
        elif stats['total_responses'] < stats['total_complaints'] / 2:
            report += f"⚠️ **Low response rate** - Only {self._calculate_rate(stats['total_responses'], stats['total_complaints'])} of complaints received responses.\n\n"
        else:
            report += f"✅ **Good engagement** - {self._calculate_rate(stats['total_responses'], stats['total_complaints'])} response rate.\n\n"
        
        report += f"""
---

*Report generated by XGrivanceMon on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        
        return report
    
    def _calculate_rate(self, numerator: int, denominator: int) -> str:
        """Calculate percentage rate"""
        if denominator == 0:
            return "0%"
        return f"{(numerator / denominator * 100):.1f}%"
    
    def generate_dashboard_summary(self, all_stats: List[Dict]) -> str:
        """Generate dashboard summary for all authorities"""
        total_complaints = sum(s['total_complaints'] for s in all_stats)
        total_responses = sum(s['total_responses'] for s in all_stats)
        
        return f"""# Transport Grievance Monitoring Dashboard

## Weekly Overview ({datetime.now().strftime('%B %d, %Y')})

| Authority | Complaints | Responses | Rate |
|-----------|------------|-----------|------|
""" + "\n".join([
            f"| {s['authority']['name']} | {s['total_complaints']} | {s['total_responses']} | {self._calculate_rate(s['total_responses'], s['total_complaints'])} |"
            for s in all_stats
        ]) + f"""

**Total: {total_complaints} complaints, {total_responses} responses ({self._calculate_rate(total_responses, total_complaints)})**
"""
